name = "Incompatible"
author = "BrailleBennett"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b23bd6b8a55a7475f81ba0a41160bba87d3db247789d509fe01cb11a135e6fcc"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
