name = "Visually Impaired Access Mods+Fabric"
author = "BrailleBennett"
version = "2.6.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7019abcc65519418d646bddab04ce63e82896597b893986d5f2fd5e209d58ba9"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
