name = "Visually Impaired Access Mods — Fabric"
author = "BrailleBennett"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4095f3fd6a5bf99091238007ef03b0b6624b2a73bfa0efffcce951853aef4c8"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
