name = "Visually Impaired Access Mods+Fabric"
author = "BrailleBennett"
version = "2.6.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49100108e00d74ea8875b1ee1598854c632807e781a1de83c8dde4baad27bfed"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
